# CircleCI build config example for the CircleCI Singularity orb

version: 2.1

orbs:
  singularity: singularity/singularity@dev:alpha

workflows:
  build_container_docker_base_example:
    jobs:
      - singularity/build_container_docker_base:
          from-uri: docker://busybox 
          image: busybox.sif 
          filters:
            branches:
              only: master
