# CircleCI build config example for the CircleCI Singularity orb

version: 2.1

orbs:
  singularity: singularity/singularity@1.0.1

workflows:
  build_example:
    jobs:
      - singularity/build_container_docker:
          from-uri: docker://busybox 
          image: busybox.sif 
          filters:
            branches:
              only: master

